"""energy_measurements

Revision ID: 63606a552a48
Revises: d2f23554b53c
Create Date: 2026-06-06 10:16:09.171067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63606a552a48'
down_revision: Union[str, Sequence[str], None] = 'd2f23554b53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('measurement_type', sa.String(length=50), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_measurements_device_id'), 'energy_measurements', ['device_id'], unique=False)
    op.create_index('ix_energy_measurements_device_timestamp', 'energy_measurements', ['device_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_energy_measurements_id'), 'energy_measurements', ['id'], unique=False)
    op.create_index(op.f('ix_energy_measurements_measurement_type'), 'energy_measurements', ['measurement_type'], unique=False)
    op.create_index(op.f('ix_energy_measurements_timestamp'), 'energy_measurements', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_measurements_timestamp'), table_name='energy_measurements')
    op.drop_index(op.f('ix_energy_measurements_measurement_type'), table_name='energy_measurements')
    op.drop_index(op.f('ix_energy_measurements_id'), table_name='energy_measurements')
    op.drop_index('ix_energy_measurements_device_timestamp', table_name='energy_measurements')
    op.drop_index(op.f('ix_energy_measurements_device_id'), table_name='energy_measurements')
    op.drop_table('energy_measurements')
    # ### end Alembic commands ###
